"""Compatibility facade for the caller-pumped runtime client and worker."""

from .runtime_dependencies import (
    APPLICATION_HOT as APPLICATION_HOT,
    CHANNEL_DEBUG as CHANNEL_DEBUG,
    CHANNEL_RUNTIME as CHANNEL_RUNTIME,
    COMMAND_ERROR_CODES as COMMAND_ERROR_CODES,
    COMPILED_CACHE_PERSIST_DELAY_NS as COMPILED_CACHE_PERSIST_DELAY_NS,
    COMPILED_CACHE_RETRY_NS as COMPILED_CACHE_RETRY_NS,
    CORE_STARTUP_PHASES as CORE_STARTUP_PHASES,
    DEBUG_VERSION as DEBUG_VERSION,
    DIAGNOSIS_EXPORT_STAGES as DIAGNOSIS_EXPORT_STAGES,
    DIAGNOSIS_PROGRESS_STAGE_BY_EXPORT as DIAGNOSIS_PROGRESS_STAGE_BY_EXPORT,
    RUNTIME_EXPORT_KIND as RUNTIME_EXPORT_KIND,
    RUNTIME_VERSION as RUNTIME_VERSION,
    SERVICE_KINDS as SERVICE_KINDS,
    SNAPSHOT_INELIGIBLE_REASONS as SNAPSHOT_INELIGIBLE_REASONS,
    STATE_EXPORT_CHUNK_BYTES as STATE_EXPORT_CHUNK_BYTES,
    STATE_IMPORT_CHUNK_BYTES as STATE_IMPORT_CHUNK_BYTES,
    FULL_PROJECT_MANIFEST_CHUNK_BYTES as FULL_PROJECT_MANIFEST_CHUNK_BYTES,
    AtomicExportStream as AtomicExportStream,
    ConfigurationChange as ConfigurationChange,
    ConfigurationSnapshot as ConfigurationSnapshot,
    DiagnosisExport as DiagnosisExport,
    DiagnosisProgress as DiagnosisProgress,
    DiagnosisProgressStage as DiagnosisProgressStage,
    ExportStage as ExportStage,
    FrontendCommand as FrontendCommand,
    FrontendEvent as FrontendEvent,
    FullProjectExport as FullProjectExport,
    GameInformation as GameInformation,
    PendingConfigurationFinalize as PendingConfigurationFinalize,
    PendingConfigurationPrepare as PendingConfigurationPrepare,
    PendingGameInput as PendingGameInput,
    PendingStateImport as PendingStateImport,
    PreparedConfiguration as PreparedConfiguration,
    PreparedConfigurationAbort as PreparedConfigurationAbort,
    PreparedConfigurationCommit as PreparedConfigurationCommit,
    PresentationBatch as PresentationBatch,
    ProjectBundle as ProjectBundle,
    RuntimeAbi as RuntimeAbi,
    RuntimeFailure as RuntimeFailure,
    ServicePresentationModel as ServicePresentationModel,
    StorageBackend as StorageBackend,
    _debug_action_owner as _debug_action_owner,
    atomic_write as atomic_write,
    debug_message as debug_message,
    decode as decode,
    decode_envelope as decode_envelope,
    decode_image_metadata as decode_image_metadata,
    diagnosis_project_name as diagnosis_project_name,
    emit_startup_milestone as emit_startup_milestone,
    encode as encode,
    encode_envelope as encode_envelope,
    enum_list_text as enum_list_text,
    enum_text as enum_text,
    format_project_diagnostic as format_project_diagnostic,
    html_printed_str as html_printed_str,
    is_message_skip_wait as is_message_skip_wait,
    is_message_wait as is_message_wait,
    log_event as log_event,
    message_value as message_value,
    message_wait_intent as message_wait_intent,
    plain_line as plain_line,
    runtime_log_level as runtime_log_level,
    runtime_message as runtime_message,
    time as time,
    unwrap_variant as unwrap_variant,
    variant as variant,
    version_range as version_range,
    write_diagnosis_archive as write_diagnosis_archive,
)
from .runtime_client import RuntimeClient as RuntimeClient
from .worker import RuntimeWorker as RuntimeWorker

RuntimeClient.__module__ = __name__
